Test download-link-check-deploy.yml

diff --git a/.github/workflows/download-link-check-deploy.yml b/.github/workflows/download-link-check-deploy.yml
--- a/.github/workflows/download-link-check-deploy.yml
+++ b/.github/workflows/download-link-check-deploy.yml
@@ -1,23 +1,31 @@
 name: DVC Download Link Check
 
 on:
-  deployment_status:
+  # deployment_status:
+  pull_request:
 
 jobs:
   run:
     name: Initialize
     runs-on: ubuntu-latest
-    if:
-      github.event.deployment.ref != 'master' &&
-      github.event.deployment_status.state == 'success'
+    # if:
+    #   github.event.deployment.ref != 'master' &&
+    #   github.event.deployment_status.state == 'success'
     steps:
       - uses: actions/checkout@v2
       - name: Download Link Checker
         uses: lycheeverse/lychee-action@v1.0.8
         with:
           args:
-            --verbose "${{ github.event.deployment.payload.web_url }}"
-            --base-url "${{ github.event.deployment.payload.web_url }}"
-            --include /download/
+            https://dvc.org/ --base-url https://dvc.org/
+            #--verbose "${{ github.event.deployment.payload.web_url }}"
+            # --base-url "${{ github.event.deployment.payload.web_url }}"
+            # --include /download/
+
         env:
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
+      - name: Check for Error Report
+        if: hashFiles('./lychee/out.md') != ''
+        run: |
+          echo 'Errors were reported while checking the availability of links.'
+          exit 1
